name: "On Push"

on: [push]

jobs:

  test-python:
    name: Test Python
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory: [
          "./lib/project01",
          "./lib/project02"
        ]
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - uses: actions/checkout@v2
        with:
          # by default actions/checkout gets a shallow copy, since we do a git diff between
          # feature-branch and common ancestor in master, we need get history
          fetch-depth: '0'
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-in-project: true
          version: 1.1.4
      - name: Install dependencies
        run: poetry install
      - name: Run pytest
        run: |
          source .venv/bin/activate
          pytest --cov-branch --cov=$(basename $PWD) --cov-report= tests/
      - name: Generate report
        id: generate_report
        # $files will receive a list of all .py files changed in project folder by the pr with exception
        # of files in tests/ folder. then it will remove part of the path and replace newline with ','
        # to use it as filter for coverage report.
        # [[ ! -z $files ]] is to check whether the specific project has files changed.
        # the output of report needs to have newline replaced, because github actions does not
        # accept multiline strings as output of steps.
        run: |
          files=$(git diff --name-only --merge-base origin/master -- '*.py' ':!tests/' | cat | grep -oP "^$(echo ${{ matrix.directory }} | cut -c3-)\/\K.*")
          source .venv/bin/activate
          report=""
          [[ ! -z $files ]] && report=$(coverage report --include=${files//$'\n'/','})

      - name: Create commit comment
        if: ${{ steps.generate_report.outputs.coverage_result != '' }}
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            Coverage Report of ${{ matrix.directory }}
            ```
            ${{ steps.generate_report.outputs.coverage_result }}
            ```
  test-unit:
    name: Unit tests
    if: ${{ always() }}
    needs:
      - test-python
    runs-on: ubuntu-latest
    steps:
      - name: Python unit tests
        if: ${{ needs.test-python.result != 'success' }}
        run: exit 1
