name: "On Push"

on: [push]

jobs:

  test-python:
    name: Test Python
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory: [
          "./lib/project01",
          "./lib/project02"
        ]
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - uses: actions/checkout@v2
        with:
          # by default actions/checkout gets a shallow copy, since we do a git diff between
          # feature-branch and common ancestor in master, we need get history
          fetch-depth: '0'
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-in-project: true
          version: 1.1.4
      - name: Install dependencies
        run: poetry install
      - name: Run pytest
        run: |
          source .venv/bin/activate
          if [ -r envs ]; then
              source envs
          fi
          pytest --cov-branch --cov=$(basename $PWD) --cov-report=xml tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          #token: ${{ secrets.CODECOV_TOKEN }}
          #fail_ci_if_error: true
          #files: ./coverage1.xml,./coverage2.xml
          flags: ${{ matrix.directory }}, unit-tests
          name: ${{ matrix.directory }}
          verbose: true
  test-unit:
    name: Unit tests
    if: ${{ always() }}
    needs:
      - test-python
    runs-on: ubuntu-latest
    steps:
      - name: Python unit tests
        if: ${{ needs.test-python.result != 'success' }}
        run: exit 1
